### ISSUE TITLE
Logging in on telldus.com redirects to the wrong /authorize endpoint

### ISSUE THREAD

**Issue by berlund** [mifi/telldus-local-auth#2]
When trying to fetch a local access token, I am redirected to the Telldus login page which in turn redirects (after logging in successfully) to

`http://<IP>/tellduslive/authorize`

which gives a 404. Where is this endpoint supposed to be?

**Comment by mifi** [comment]
did u follow instructions? https://github.com/johnlemonse/homebridge-telldus?tab=readme-ov-file#local-configuration

**Comment by berlund** [comment]
Yes, it is the redirect from telldus.com that seems to be incorrect (see above)

Running gateway fw v1.3.2

**Comment by berlund** [comment]
I tested again, following the same steps and this time it worked. Noticing that this time telldus.com redirected me to `http://<IP>/api/authorize` which is the correct one.
